name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Set a branch to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website' # This is the directory containing your website files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
